### ISSUE TITLE
Restrict Entity-Ceation using Helm Chart

### ISSUE THREAD

**Issue by emcellsoft** [eclipse/ditto#1443]
I'm trying to use "Restrict Entity-Creation" like mentioned [here](https://www.eclipse.org/ditto/installation-operating.html#restricting-entity-creation)

I'm using the official [Helm Chart](https://github.com/eclipse/packages/tree/master/charts/ditto) to run ditto. 

I'm not sure how to integrate the entity-creation config. 

What I've tried so far issSetting the config via systemProps. I was not sure which service is responsible for restricting enity creation. So I added it to all services.

values.yaml
```yaml
gateway:
  systemProps:
      - "-Dditto.entity-creation.grant.0.auth-subjects.0=admins:role/admin"
policies:
  systemProps:
      - "-Dditto.entity-creation.grant.0.auth-subjects.0=admins:role/admin"
concierge:
  systemProps:
      - "-Dditto.entity-creation.grant.0.auth-subjects.0=admins:role/admin"
things:
  systemProps:
      - "-Dditto.entity-creation.grant.0.auth-subjects.0=admins:role/admin"
connectivity:
  systemProps:
      - "-Dditto.entity-creation.grant.0.auth-subjects.0=admins:role/admin"
```

This doesn't work.

I've also tried adding `- "-Dditto.entity-creation.revoke.0={}"` and hoped this would revoke entity creation for all users. Had no success on this. 

The helm chart does not supply any options to add configuration files to the services. So also no luck with this. 

Do you have any Tipps?

Edit:

I've modified the helm chart in order to add a `ditto-entity-creation.conf` into  the working directory (opt/ditto) of each service. 

ditto-entity-creation.conf:
```
ditto.entity-creation {
  grant = [
      {
        resource-types = [],
        namespace = []
        auth-subjects = ["admins:*"]
      }
  ]
  revoke = [
      # same as "grant", but rejecting requests which already passed "grant"
  ]
}
```

Doesn't help.

**Comment by thjaeckle** [comment]
Hi @emcellsoft 

Thanks for trying out Ditto.
You are right - with the linked documentation at 
https://www.eclipse.org/ditto/installation-operating.html#restricting-entity-creation
you won't be able to configure the entity-creation correctly.

That is the latest "development" documentation (also as stated in the upper left of the site) and we recently adjusted for the upcoming Ditto 3.0 the configuration.
For Ditto 2.4 (which you are most likely using), please find the documentation here:
https://www.eclipse.org/ditto/2.4/installation-operating.html#restricting-entity-creation

You only have to configure the system-property for the "concierge" service (which will be removed from Ditto 3.0 - that's why we had to adjust the configuration as well) - and you did it already correctly:
```yaml
concierge:
  systemProps:
      - "-Dditto.concierge.enforcement.entity-creation.grant.0.auth-subjects.0=admins:role/admin"
```

That will cause that only a user which somehow received the "auth subject" `"admins:role/admin"` may create "policies" and "things".
