### ISSUE TITLE
Having trouble adding oauth configuration via docker-compose.yml

### ISSUE THREAD

**Issue by raujonas** [eclipse/ditto#876]
Hello! I'm having trouble with adding an oauth configuration with the prebuilt docker images. What I tried is adding these two lines to the gateway service in the docker-compose.yml like described here [https://www.eclipse.org/ditto/installation-operating.html#openid-connect](https://www.eclipse.org/ditto/installation-operating.html#openid-connect)
```
      - Dditto.gateway.authentication.oauth.protocol=http
      - Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak=keycloak.localhost:8090/auth/realms/twin
```
Complete service configuration:
```
  gateway:
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
      - concierge
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - ENABLE_DUMMY_AUTH=true
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      # You may use the environment for setting the devops password
      #- DEVOPS_PASSWORD=foobar
    # Set additional configuration options here
    # -Dditto.gateway...
      - Dditto.gateway.authentication.oauth.protocol=http
      - Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak=keycloak.localhost:8090/auth/realms/twin
    # Setting the devops password via java VM environment
    command: java -Dditto.gateway.authentication.devops.password=foobar -jar starter.jar
```
This results in the following http error if I try to use the api with postman:
```
{
    "status": 401,
    "error": "gateway:jwt.issuer.notsupported",
    "message": "The JWT issuer 'http://keycloak.localhost:8090/auth/realms/twin' is not supported.",
    "description": "Check if your JWT is correct."
}
```
However if I build the docker images locally and add the following part in the gateway.conf it works:
```
ditto {
  ...
  gateway {
    ...
    authentication {
    ...
      oauth {
        protocol = "http"
        openid-connect-issuers = {
          keycloak = "keycloak.localhost:8090/auth/realms/twin"
        }
      }
  ...
```
What am I missing here? Is there something wrong with my environment variables?

**Comment by thjaeckle** [comment]
Hi.

There is something wrong with your environment variables ;)

Correct would be:
```yaml
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - ENABLE_DUMMY_AUTH=true
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      # You may use the environment for setting the devops password
      #- DEVOPS_PASSWORD=foobar
    # Set additional configuration options here
    # -Dditto.gateway...
    # Setting the devops password via java VM environment
    command: java -Dditto.gateway.authentication.devops.password=foobar -Dditto.gateway.authentication.oauth.protocol=http -Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak=keycloak.localhost:8090/auth/realms/twin -jar starter.jar
```

The inline comment probably doesn't make that quite clear that those `-D` configuration have to be set at the `"command"` level.
